backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: 'author'
    label: 'Author'
    folder: 'src/pages/author'
    create: false
    fields:
      - {
          label: 'Template Key',
          name: 'templateKey',
          widget: 'hidden',
          default: 'author-page',
        }
      - { label: 'Name', name: 'name', widget: 'string' }
      - { label: 'Email', name: 'email', widget: 'string' }
      - {
          label: 'Twitter Handle',
          name: 'twitterHandle',
          widget: 'string',
          required: false,
          pattern: '^@?(\w){1,15}$',
        }

  - name: 'blog'
    label: 'Blog'
    folder: 'src/pages/blog'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - {
          label: 'Template Key',
          name: 'templateKey',
          widget: 'hidden',
          default: 'blog-post',
        }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Image', name: 'image', widget: 'image', required: false }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - {
          label: 'Description',
          name: 'description',
          widget: 'text',
          required: false,
        }
      - { label: 'Body', name: 'body', widget: 'markdown', required: false }
      - { label: 'Tags', name: 'tags', widget: 'list', required: false }
      - {
          label: 'Post Author',
          name: 'author',
          widget: 'relation',
          collection: 'author',
          searchFields: ['name', 'twitterHandle', 'email'],
          valueField: 'name',
          required: false,
          displayFields: ['name', 'email', 'twitterHandle'],
        }

  - name: 'pages'
    label: 'Pages'
    files:
      - file: 'src/pages/about/index.md'
        label: 'About'
        name: 'about'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'about-page',
            }
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }